rw le_iff_exists_add at hab hba,
cases hab with d hd,
cases hba with e he,
rw hd at he,
symmetry at he,
rw add_assoc at he,
have p := eq_zero_of_add_right_eq_self he,
have q := add_right_eq_zero p,
rw q at hd,
rw add_zero at hd,
symmetry at hd,
exact hd,
